#!/bin/bash

# Delete blacklist number

if [ "$1" = "" ]; then
  echo ""
  echo "Usage: $0 phone-number"
  echo ""
  exit 1
fi

echo ""
echo -n "Delete $1 from Asterisk blacklist (y/n)? "
while read -r -n 1 -s answer; do
  if [[ ${answer} = [yYnN] ]]; then
    echo "${answer}"
    if [[ ${answer} = [yY] ]]; then
      break
    else
      echo ""
      echo "Aborted"
      echo ""
      exit 1
    fi
  fi
done

echo ""
asterisk -rx "database deltree blacklist $1"
echo ""
