#!/bin/bash

errexit()
{
  echo ""
  echo "$1"
  echo ""
  exit 1
}

if [ $(id -u) -ne 0 ]; then
  errexit "Must be run as root user: sudo $0"
fi
if [ "$(uname -m)" != "aarch64" ]; then
  errexit "O/S is not Raspberry Pi OS (64 bit)"
fi
if [[ ! -h /sbin/halt || ! -h /sbin/poweroff ]]; then
  errexit "halt and/or poweroff not a symlink"
fi
mv /sbin/halt /sbin/halt_orig
mv /sbin/poweroff /sbin/poweroff_orig
cat <<EOF > /sbin/halt
#!/bin/bash

/sbin/poweroff_orig
EOF
cat <<EOF > /sbin/poweroff
#!/bin/bash

/sbin/halt_orig
EOF
chmod +x /sbin/halt /sbin/poweroff
