#!/bin/bash

if command -v systemctl > /dev/null && systemctl | grep -q '\-\.mount'; then
  SYSTEMD=1
elif [ -f /etc/init.d/cron ] && [ ! -h /etc/init.d/cron ]; then
  SYSTEMD=0
else
  echo ""
  echo "Unrecognized init system"
  echo ""
  exit 1
fi

FLAG=0
if [ -s /etc/iptables/ipt-dat ]; then
  while read DATIP DATFQDN; do
    if [ "${DATFQDN}" != "" ]; then
      IP=`nslookup ${DATFQDN} | tail -2 | cut -f 2 -d " " | head -n 1`
      if [[ "${IP}" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        if [ "${IP}" != "${DATIP}" ]; then
          sed -i "s/^\(.*\)${DATIP}\(.*\"ipt-add : ${DATFQDN}\"\)$/\1${IP}\2/" /etc/iptables/rules.v4
          sed -i "s/^${DATIP} ${DATFQDN}$/${IP} ${DATFQDN}/" /etc/iptables/ipt-dat
          FLAG=1
        fi
      fi
    fi
  done < /etc/iptables/ipt-dat
fi
if [ ${FLAG} -eq 1 ]; then
  while :
  do
    if [ ${SYSTEMD} -eq 1 ]; then
      invoke-rc.d netfilter-persistent restart &> /dev/null
      STATUS=`systemctl status netfilter-persistent.service | tail -1 | grep "failed"`
    else
      STATUS=`service iptables restart | grep "fail"`
    fi
    if [ "${STATUS}" = "" ]; then
      echo ""
      echo "iptables successfully restarted"
      echo ""
      break
    fi
    iptables-restore /etc/iptables/rules.v4 2> /tmp/ipt-err
    ERROR=`cat /tmp/ipt-err`
    if [[ "${ERROR}" == *Error* ]]; then
      LINE=`cat /tmp/ipt-err | cut -f 2 -d ":" | tail -2 | head -n 1 | tr -d ' '`
      sed -i "${LINE} s/^/# Error: /" /etc/iptables/rules.v4
      echo ""
      cat /tmp/ipt-err | head -n -1
    fi
    rm /tmp/ipt-err
  done
fi
