#!/bin/bash

echo ""
echo -n "Remove Network UPS Tools (y/n)? "
while read -r -n 1 -s answer; do
  if [[ ${answer} = [yYnN] ]]; then
    echo "${answer}"
    if [[ ${answer} = [yY] ]]; then
      break
    else
      echo ""
      echo "Aborted"
      echo ""
      exit 1
    fi
  fi
done

echo ""
apt-get -y update
apt-get -y purge nut
apt-get -y purge nut-client
apt-get -y autoremove
rm -r /etc/nut &> /dev/null
rm /root/ups-info &> /dev/null
rm /root/ups-ctrl &> /dev/null

echo ""
