#!/bin/bash

errexit()
{
  echo ""
  echo "$1"
  echo ""
  echo "Usage: $0 file device"
  echo ""
  exit 1
}

if [ $(id -u) -ne 0 ]; then
  errexit "$0 must be run as root user"
fi
if [ ! -f "$1" ]; then
  errexit "File not found: $1"
fi
if [[ (! "$2" =~ ^/dev/sd[a-z]$ && ! "$2" =~ ^/dev/nvme[0-9]n1$ && ! "$2" =~ ^/dev/mmcblk0$) || ! -b "$2" ]]; then
  errexit "Invalid device: $2"
fi
if [ $(mount | grep -c "^$2") -ne 0 ]; then
  errexit "$2 is in use (mounted)"
fi
echo ""
echo -n "Ok to write $1 to $2 (y/n)? "
while read -r -n 1 -s answer; do
  if [[ "${answer}" = [yYnN] ]]; then
    echo "${answer}"
    if [[ "${answer}" = [yY] ]]; then
      break
    else
      errexit "Aborted"
      exit 1
    fi
  fi
done
echo ""
dd bs=4M if="$1" of="$2" status=progress
sync
echo 3 > /proc/sys/vm/drop_caches
FILESIZE=$(ls -l "$1" | awk '{print $5}')
echo ""
echo "Comparing $2 to $1 (${FILESIZE} bytes)"
cmp -n ${FILESIZE} "$2" "$1"
echo ""
